# TESTING TAPAS ATTACKS

In [15]:
!pip install -r ./requirements.txt

Collecting tapas@ git+https://github.com/alan-turing-institute/privacy-sdg-toolbox@a7069d7e040828db0da174d1b003fa03a98e5453 (from -r ./requirements.txt (line 135))
  Cloning https://github.com/alan-turing-institute/privacy-sdg-toolbox (to revision a7069d7e040828db0da174d1b003fa03a98e5453) to /private/var/folders/6q/2r6m8pvx5wsd73wrfykl83sh0000gn/T/pip-install-o_1w5qoc/tapas_615bb1d1a02d4b40b6558b0cf902345c
  Running command git clone --filter=blob:none --quiet https://github.com/alan-turing-institute/privacy-sdg-toolbox /private/var/folders/6q/2r6m8pvx5wsd73wrfykl83sh0000gn/T/pip-install-o_1w5qoc/tapas_615bb1d1a02d4b40b6558b0cf902345c
  Running command git rev-parse -q --verify 'sha^a7069d7e040828db0da174d1b003fa03a98e5453'
  Running command git fetch -q https://github.com/alan-turing-institute/privacy-sdg-toolbox a7069d7e040828db0da174d1b003fa03a98e5453
  Resolved https://github.com/alan-turing-institute/privacy-sdg-toolbox to commit a7069d7e040828db0da174d1b003fa03a98e5453
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting aiofiles==22.1.0 (from -r ./requirements.txt (line 1))
  Using cached aiofiles-22.1.0-py3-none-any.whl.metadata (8.0 kB)
Collecting aiosqlite==0.21.0 (from -r ./requirements.txt (line 2))
  Using cached aiosqlite-0.21.0-py3-none-any.whl.metadata (4.3 kB)
Collecting anyio==4.9.0 (from -r ./requirements.txt (line 3))
  Using cached anyio-4.9.0-py3-none-any.whl.metadata (4.7 kB)
Collecting argon2-cffi==23.1.0 (from -r ./requirements.txt (line 4))
  Using cached argon2_cffi-23.1.0-py3-none-any.whl.metadata (5.2 kB)
Collecting argon2-cffi-bindings==21.2.0 (from -r ./requirements.txt (line 5))
  Using cached argon2_cffi_bindings-21.2.0-cp38-abi3-macosx_10_9_universal2.whl.metadata (6.7 kB)
Collecting arrow==1.3.0 (from -r ./requirements.txt (line 6))
  Using cached arrow-1.3.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: asttokens==3.0.0 in /Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages (from -r ./requirements.txt (line 7)) (3.0.0)
Collecting attrs==25.3.0 (from -r ./requirements.txt (line 8))
  Using cached attrs-25.3.0-py3-none-any.whl.metadata (10 kB)
Collecting babel==2.17.0 (from -r ./requirements.txt (line 9))
  Using cached babel-2.17.0-py3-none-any.whl.metadata (2.0 kB)
Collecting beautifulsoup4==4.13.4 (from -r ./requirements.txt (line 10))
  Using cached beautifulsoup4-4.13.4-py3-none-any.whl.metadata (3.8 kB)
Collecting bleach==6.2.0 (from -r ./requirements.txt (line 11))
  Using cached bleach-6.2.0-py3-none-any.whl.metadata (30 kB)
Collecting boto3==1.38.8 (from -r ./requirements.txt (line 12))
  Using cached boto3-1.38.8-py3-none-any.whl.metadata (6.6 kB)
Collecting botocore==1.38.8 (from -r ./requirements.txt (line 13))
  Using cached botocore-1.38.8-py3-none-any.whl.metadata (5.7 kB)
Collecting certifi==2025.4.26 (from -r ./requirements.txt (line 14))
  Using cached certifi-2025.4.26-py3-none-any.whl.metadata (2.5 kB)
Collecting cffi==1.17.1 (from -r ./requirements.txt (line 15))
  Using cached cffi-1.17.1-cp310-cp310-macosx_10_9_x86_64.whl.metadata (1.5 kB)
Collecting charset-normalizer==3.4.1 (from -r ./requirements.txt (line 16))
  Using cached charset_normalizer-3.4.1-cp310-cp310-macosx_10_9_universal2.whl.metadata (35 kB)
Collecting cloudpickle==3.1.1 (from -r ./requirements.txt (line 17))
  Using cached cloudpickle-3.1.1-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: comm==0.2.2 in /Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages (from -r ./requirements.txt (line 18)) (0.2.2)
Collecting contourpy==1.3.2 (from -r ./requirements.txt (line 19))
  Using cached contourpy-1.3.2-cp310-cp310-macosx_10_9_x86_64.whl.metadata (5.5 kB)
Collecting copulas==0.12.2 (from -r ./requirements.txt (line 20))
  Using cached copulas-0.12.2-py3-none-any.whl.metadata (9.4 kB)
Collecting ctgan==0.11.0 (from -r ./requirements.txt (line 21))
  Using cached ctgan-0.11.0-py3-none-any.whl.metadata (10 kB)
Collecting cycler==0.12.1 (from -r ./requirements.txt (line 22))
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: debugpy==1.8.14 in /Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages (from -r ./requirements.txt (line 23)) (1.8.14)
Requirement already satisfied: decorator==5.2.1 in /Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages (from -r ./requirements.txt (line 24)) (5.2.1)
Collecting deepecho==0.7.0 (from -r ./requirements.txt (line 25))
  Using cached deepecho-0.7.0-py3-none-any.whl.metadata (10 kB)
Collecting defusedxml==0.7.1 (from -r ./requirements.txt (line 26))
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB)
Collecting domias==0.0.5 (from -r ./requirements.txt (line 27))
  Using cached domias-0.0.5-py3-none-macosx_10_14_x86_64.whl.metadata (6.5 kB)
Collecting entrypoints==0.4 (from -r ./requirements.txt (line 28))
  Using cached entrypoints-0.4-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: exceptiongroup==1.2.2 in /Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages (from -r ./requirements.txt (line 29)) (1.2.2)
Requirement already satisfied: executing==2.2.0 in /Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages (from -r ./requirements.txt (line 30)) (2.2.0)
Collecting Faker==37.1.0 (from -r ./requirements.txt (line 31))
  Using cached faker-37.1.0-py3-none-any.whl.metadata (15 kB)
Collecting fastjsonschema==2.21.1 (from -r ./requirements.txt (line 32))
  Using cached fastjsonschema-2.21.1-py3-none-any.whl.metadata (2.2 kB)
Collecting filelock==3.18.0 (from -r ./requirements.txt (line 33))
  Using cached filelock-3.18.0-py3-none-any.whl.metadata (2.9 kB)
Collecting fonttools==4.57.0 (from -r ./requirements.txt (line 34))
  Using cached fonttools-4.57.0-cp310-cp310-macosx_10_9_x86_64.whl.metadata (102 kB)
Collecting fqdn==1.5.1 (from -r ./requirements.txt (line 35))
  Using cached fqdn-1.5.1-py3-none-any.whl.metadata (1.4 kB)
Collecting fsspec==2025.3.2 (from -r ./requirements.txt (line 36))
  Using cached fsspec-2025.3.2-py3-none-any.whl.metadata (11 kB)
Collecting geomloss==0.2.6 (from -r ./requirements.txt (line 37))
  Using cached geomloss-0.2.6.tar.gz (26 kB)
  Preparing metadata (setup.py) ... done
Collecting graphviz==0.20.3 (from -r ./requirements.txt (line 38))
  Using cached graphviz-0.20.3-py3-none-any.whl.metadata (12 kB)
Collecting idna==3.10 (from -r ./requirements.txt (line 39))
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: ipykernel==6.29.5 in /Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages (from -r ./requirements.txt (line 40)) (6.29.5)
Requirement already satisfied: ipython==8.36.0 in /Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages (from -r ./requirements.txt (line 41)) (8.36.0)
Collecting ipython-genutils==0.2.0 (from -r ./requirements.txt (line 42))
  Using cached ipython_genutils-0.2.0-py2.py3-none-any.whl.metadata (755 bytes)
Collecting isoduration==20.11.0 (from -r ./requirements.txt (line 43))
  Using cached isoduration-20.11.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: jedi==0.19.2 in /Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages (from -r ./requirements.txt (line 44)) (0.19.2)
Collecting Jinja2==3.1.6 (from -r ./requirements.txt (line 45))
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting jmespath==1.0.1 (from -r ./requirements.txt (line 46))
  Using cached jmespath-1.0.1-py3-none-any.whl.metadata (7.6 kB)
Collecting joblib==1.4.2 (from -r ./requirements.txt (line 47))
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting json5==0.12.0 (from -r ./requirements.txt (line 48))
  Using cached json5-0.12.0-py3-none-any.whl.metadata (36 kB)
Collecting jsonpointer==3.0.0 (from -r ./requirements.txt (line 49))
  Using cached jsonpointer-3.0.0-py2.py3-none-any.whl.metadata (2.3 kB)
Collecting jsonschema==4.23.0 (from -r ./requirements.txt (line 50))
  Using cached jsonschema-4.23.0-py3-none-any.whl.metadata (7.9 kB)
Collecting jsonschema-specifications==2025.4.1 (from -r ./requirements.txt (line 51))
  Using cached jsonschema_specifications-2025.4.1-py3-none-any.whl.metadata (2.9 kB)
Collecting jupyter-events==0.12.0 (from -r ./requirements.txt (line 52))
  Using cached jupyter_events-0.12.0-py3-none-any.whl.metadata (5.8 kB)
Collecting jupyter-ydoc==0.2.5 (from -r ./requirements.txt (line 53))
  Using cached jupyter_ydoc-0.2.5-py3-none-any.whl.metadata (2.2 kB)
Collecting jupyter_client==7.4.9 (from -r ./requirements.txt (line 54))
  Using cached jupyter_client-7.4.9-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: jupyter_core==5.7.2 in /Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages (from -r ./requirements.txt (line 55)) (5.7.2)
Collecting jupyter_server==2.15.0 (from -r ./requirements.txt (line 56))
  Using cached jupyter_server-2.15.0-py3-none-any.whl.metadata (8.4 kB)
Collecting jupyter_server_fileid==0.9.3 (from -r ./requirements.txt (line 57))
  Using cached jupyter_server_fileid-0.9.3-py3-none-any.whl.metadata (4.7 kB)
Collecting jupyter_server_terminals==0.5.3 (from -r ./requirements.txt (line 58))
  Using cached jupyter_server_terminals-0.5.3-py3-none-any.whl.metadata (5.6 kB)
Collecting jupyter_server_ydoc==0.8.0 (from -r ./requirements.txt (line 59))
  Using cached jupyter_server_ydoc-0.8.0-py3-none-any.whl.metadata (5.3 kB)
Collecting jupyterlab==3.6.8 (from -r ./requirements.txt (line 60))
  Using cached jupyterlab-3.6.8-py3-none-any.whl.metadata (12 kB)
Collecting jupyterlab_pygments==0.3.0 (from -r ./requirements.txt (line 61))
  Using cached jupyterlab_pygments-0.3.0-py3-none-any.whl.metadata (4.4 kB)
Collecting jupyterlab_server==2.27.3 (from -r ./requirements.txt (line 62))
  Using cached jupyterlab_server-2.27.3-py3-none-any.whl.metadata (5.9 kB)
Collecting kiwisolver==1.4.8 (from -r ./requirements.txt (line 63))
  Using cached kiwisolver-1.4.8-cp310-cp310-macosx_10_9_x86_64.whl.metadata (6.2 kB)
Collecting MarkupSafe==3.0.2 (from -r ./requirements.txt (line 64))
  Using cached MarkupSafe-3.0.2-cp310-cp310-macosx_10_9_universal2.whl.metadata (4.0 kB)
Collecting matplotlib==3.10.1 (from -r ./requirements.txt (line 65))
  Using cached matplotlib-3.10.1-cp310-cp310-macosx_10_12_x86_64.whl.metadata (11 kB)
Requirement already satisfied: matplotlib-inline==0.1.7 in /Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages (from -r ./requirements.txt (line 66)) (0.1.7)
Collecting mistune==3.1.3 (from -r ./requirements.txt (line 67))
  Using cached mistune-3.1.3-py3-none-any.whl.metadata (1.8 kB)
Collecting mpmath==1.3.0 (from -r ./requirements.txt (line 68))
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Collecting narwhals==1.37.1 (from -r ./requirements.txt (line 69))
  Using cached narwhals-1.37.1-py3-none-any.whl.metadata (9.3 kB)
Collecting nbclassic==1.3.0 (from -r ./requirements.txt (line 70))
  Using cached nbclassic-1.3.0-py3-none-any.whl.metadata (5.5 kB)
Collecting nbclient==0.5.13 (from -r ./requirements.txt (line 71))
  Using cached nbclient-0.5.13-py3-none-any.whl.metadata (5.0 kB)
Collecting nbconvert==7.16.6 (from -r ./requirements.txt (line 72))
  Using cached nbconvert-7.16.6-py3-none-any.whl.metadata (8.5 kB)
Collecting nbformat==5.10.4 (from -r ./requirements.txt (line 73))
  Using cached nbformat-5.10.4-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: nest-asyncio==1.6.0 in /Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages (from -r ./requirements.txt (line 74)) (1.6.0)
Collecting networkx==3.4.2 (from -r ./requirements.txt (line 75))
  Using cached networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)
Collecting notebook==6.5.7 (from -r ./requirements.txt (line 76))
  Using cached notebook-6.5.7-py3-none-any.whl.metadata (2.5 kB)
Collecting notebook_shim==0.2.4 (from -r ./requirements.txt (line 77))
  Using cached notebook_shim-0.2.4-py3-none-any.whl.metadata (4.0 kB)
Collecting numpy==1.26.4 (from -r ./requirements.txt (line 78))
  Using cached numpy-1.26.4-cp310-cp310-macosx_10_9_x86_64.whl.metadata (61 kB)
Collecting overrides==7.7.0 (from -r ./requirements.txt (line 93))
  Using cached overrides-7.7.0-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: packaging==25.0 in /Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages (from -r ./requirements.txt (line 94)) (25.0)
Collecting palettable==3.3.3 (from -r ./requirements.txt (line 95))
  Using cached palettable-3.3.3-py2.py3-none-any.whl.metadata (3.3 kB)
Collecting pandas==1.5.3 (from -r ./requirements.txt (line 96))
  Using cached pandas-1.5.3-cp310-cp310-macosx_10_9_x86_64.whl.metadata (11 kB)
Collecting pandocfilters==1.5.1 (from -r ./requirements.txt (line 97))
  Using cached pandocfilters-1.5.1-py2.py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: parso==0.8.4 in /Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages (from -r ./requirements.txt (line 98)) (0.8.4)
Requirement already satisfied: pexpect==4.9.0 in /Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages (from -r ./requirements.txt (line 99)) (4.9.0)
Collecting pillow==11.2.1 (from -r ./requirements.txt (line 100))
  Using cached pillow-11.2.1-cp310-cp310-macosx_10_10_x86_64.whl.metadata (8.9 kB)
Requirement already satisfied: platformdirs==4.3.7 in /Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages (from -r ./requirements.txt (line 101)) (4.3.7)
Collecting plotly==6.0.1 (from -r ./requirements.txt (line 102))
  Using cached plotly-6.0.1-py3-none-any.whl.metadata (6.7 kB)
Collecting prometheus_client==0.21.1 (from -r ./requirements.txt (line 103))
  Using cached prometheus_client-0.21.1-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: prompt_toolkit==3.0.51 in /Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages (from -r ./requirements.txt (line 104)) (3.0.51)
Collecting protobuf==6.30.2 (from -r ./requirements.txt (line 105))
  Using cached protobuf-6.30.2-cp39-abi3-macosx_10_9_universal2.whl.metadata (593 bytes)
Requirement already satisfied: psutil==7.0.0 in /Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages (from -r ./requirements.txt (line 106)) (7.0.0)
Requirement already satisfied: ptyprocess==0.7.0 in /Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages (from -r ./requirements.txt (line 107)) (0.7.0)
Requirement already satisfied: pure_eval==0.2.3 in /Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages (from -r ./requirements.txt (line 108)) (0.2.3)
Collecting pycparser==2.22 (from -r ./requirements.txt (line 109))
  Using cached pycparser-2.22-py3-none-any.whl.metadata (943 bytes)
Requirement already satisfied: Pygments==2.19.1 in /Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages (from -r ./requirements.txt (line 110)) (2.19.1)
Collecting pyparsing==3.2.3 (from -r ./requirements.txt (line 111))
  Using cached pyparsing-3.2.3-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: python-dateutil==2.9.0.post0 in /Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages (from -r ./requirements.txt (line 112)) (2.9.0.post0)
Collecting python-json-logger==3.3.0 (from -r ./requirements.txt (line 113))
  Using cached python_json_logger-3.3.0-py3-none-any.whl.metadata (4.0 kB)
Collecting pytz==2025.2 (from -r ./requirements.txt (line 114))
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting PyYAML==6.0.2 (from -r ./requirements.txt (line 115))
  Using cached PyYAML-6.0.2-cp310-cp310-macosx_10_9_x86_64.whl.metadata (2.1 kB)
Collecting pyzmq==26.4.0 (from -r ./requirements.txt (line 116))
  Using cached pyzmq-26.4.0-cp310-cp310-macosx_10_15_universal2.whl.metadata (6.0 kB)
Collecting rdt==1.16.0 (from -r ./requirements.txt (line 117))
  Using cached rdt-1.16.0-py3-none-any.whl.metadata (10 kB)
Collecting referencing==0.36.2 (from -r ./requirements.txt (line 118))
  Using cached referencing-0.36.2-py3-none-any.whl.metadata (2.8 kB)
Collecting requests==2.32.3 (from -r ./requirements.txt (line 119))
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting rfc3339-validator==0.1.4 (from -r ./requirements.txt (line 120))
  Using cached rfc3339_validator-0.1.4-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting rfc3986-validator==0.1.1 (from -r ./requirements.txt (line 121))
  Using cached rfc3986_validator-0.1.1-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting rpds-py==0.24.0 (from -r ./requirements.txt (line 122))
  Using cached rpds_py-0.24.0-cp310-cp310-macosx_10_12_x86_64.whl.metadata (4.1 kB)
Collecting s3transfer==0.12.0 (from -r ./requirements.txt (line 123))
  Using cached s3transfer-0.12.0-py3-none-any.whl.metadata (1.7 kB)
Collecting scikit-learn==1.6.1 (from -r ./requirements.txt (line 124))
  Using cached scikit_learn-1.6.1-cp310-cp310-macosx_10_9_x86_64.whl.metadata (31 kB)
Collecting scipy==1.15.2 (from -r ./requirements.txt (line 125))
  Using cached scipy-1.15.2-cp310-cp310-macosx_14_0_x86_64.whl.metadata (61 kB)
Collecting sdmetrics==0.20.1 (from -r ./requirements.txt (line 126))
  Using cached sdmetrics-0.20.1-py3-none-any.whl.metadata (9.4 kB)
Collecting sdv==1.20.1 (from -r ./requirements.txt (line 127))
  Using cached sdv-1.20.1-py3-none-any.whl.metadata (14 kB)
Collecting seaborn==0.12.2 (from -r ./requirements.txt (line 128))
  Using cached seaborn-0.12.2-py3-none-any.whl.metadata (5.4 kB)
Collecting Send2Trash==1.8.3 (from -r ./requirements.txt (line 129))
  Using cached Send2Trash-1.8.3-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: six==1.17.0 in /Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages (from -r ./requirements.txt (line 130)) (1.17.0)
Collecting sniffio==1.3.1 (from -r ./requirements.txt (line 131))
  Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting soupsieve==2.7 (from -r ./requirements.txt (line 132))
  Using cached soupsieve-2.7-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: stack-data==0.6.3 in /Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages (from -r ./requirements.txt (line 133)) (0.6.3)
Collecting sympy==1.14.0 (from -r ./requirements.txt (line 134))
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting tensorboardX==2.6.2.2 (from -r ./requirements.txt (line 136))
  Using cached tensorboardX-2.6.2.2-py2.py3-none-any.whl.metadata (5.8 kB)
Collecting terminado==0.18.1 (from -r ./requirements.txt (line 137))
  Using cached terminado-0.18.1-py3-none-any.whl.metadata (5.8 kB)
Collecting threadpoolctl==3.6.0 (from -r ./requirements.txt (line 138))
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting tinycss2==1.4.0 (from -r ./requirements.txt (line 139))
  Using cached tinycss2-1.4.0-py3-none-any.whl.metadata (3.0 kB)
Collecting tomli==2.2.1 (from -r ./requirements.txt (line 140))
  Using cached tomli-2.2.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: tornado==6.4.2 in /Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages (from -r ./requirements.txt (line 142)) (6.4.2)
Collecting tqdm==4.67.1 (from -r ./requirements.txt (line 143))
  Using cached tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: traitlets==5.14.3 in /Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages (from -r ./requirements.txt (line 144)) (5.14.3)
Collecting types-python-dateutil==2.9.0.20241206 (from -r ./requirements.txt (line 146))
  Downloading types_python_dateutil-2.9.0.20241206-py3-none-any.whl.metadata (2.1 kB)

## Common part for attacks

In [18]:
## TAPAS TRIAL INTERFACES
import tapas.datasets
import tapas.generators
import tapas.threat_models
import tapas.attacks
import tapas.report

In [19]:
# Load the data.
data = tapas.datasets.TabularDataset.read(
    "data/2011 Census Microdata Teaching File", label="Census"
)

# Selects the target record
target_record = data.get_records([1])
data.drop_records([1], in_place=True)

# Create a dummy generator (It just samples data from original dataset)
generator = tapas.generators.Raw()

# Select the auxiliary data + black-box attack model.
data_knowledge = tapas.threat_models.AuxiliaryDataKnowledge(
    data, auxiliary_split=0.5, num_training_records=1000,
)

sdg_knowledge = tapas.threat_models.BlackBoxKnowledge(
    generator, num_synthetic_records=1000,
)

## MIA

In [20]:
# Defining a threat model 
threat_model = tapas.threat_models.TargetedMIA(
    attacker_knowledge_data=data_knowledge,
    target_record=target_record,
    attacker_knowledge_generator=sdg_knowledge,
    generate_pairs=True,
    replace_target=True,
)

attack = tapas.attacks.GroundhogAttack(
    use_hist=False, use_corr=False, label="NaiveGroundhog"
)

attack.train(threat_model,num_samples=100)
summary_mia = threat_model.test(attack, num_samples=100)
report_mia = tapas.report.MIAttackReport([summary_mia])

In [21]:
report_mia.attacks_data

,dataset,target_id,generator,attack,accuracy,true_positive_rate,false_positive_rate,mia_advantage,privacy_gain,auc,effective_epsilon
0,Census (AUX),1,Raw,NaiveGroundhog,0.53,0.5,0.44,0.06,0.94,0.5472,0.916291

## AIA

In [22]:
threat_model = tapas.threat_models.TargetedAIA(
    attacker_knowledge_data=data_knowledge,
    # Specific to AIA: the sensitive attribute and its possible values.
    sensitive_attribute="Country of Birth",
    attribute_values=["-9", "1", "2"],
    target_record=target_record,
    attacker_knowledge_generator=sdg_knowledge,
)


attack =tapas.attacks.GroundhogAttack()
attack.train(threat_model, num_samples=100)

summary_aia = threat_model.test(attack, num_samples=100)
report_aia = tapas.report.MIAttackReport([summary_aia])

/Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

In [23]:
report_aia.attacks_data

        dataset target_id generator     attack sensitive_attribute  accuracy
0  Census (AUX)         1       Raw  Groundhog    Country of Birth      0.65

## Extending repirts with new metrics

In [24]:
from sklearn.metrics import precision_score, recall_score, f1_score

### Approach 1

In [25]:
report_mia.attacks_data["f1_score"] = f1_score(summary_mia.labels, summary_mia.predictions)
report_mia.metrics.append("f1_score") # register the metric so it's included in `.metrics`

In [26]:
print(precision_score(summary_aia.labels, summary_aia.predictions, average="macro"), recall_score(summary_aia.labels, summary_aia.predictions, average="weighted"), f1_score(summary_aia.labels, summary_aia.predictions, average="micro"))
report_aia.attacks_data["precision"] =  precision_score(summary_aia.labels, summary_aia.predictions, average="macro")
report_aia.attacks_data["recall"] =  recall_score(summary_aia.labels, summary_aia.predictions, average="weighted")
report_aia.attacks_data["f1_score"] =  f1_score(summary_aia.labels, summary_aia.predictions, average="micro")

report_aia.metrics.append("precision") # register the metric so it's included in `.metrics`
report_aia.metrics.append("recall") # register the metric so it's included in `.metrics`
report_aia.metrics.append("f1_score") # register the metric so it's included in `.metrics`
report_aia.attacks_data

0.594079457364341 0.65 0.65

,dataset,target_id,generator,attack,sensitive_attribute,accuracy,precision,recall,f1_score
0,Census (AUX),1,Raw,Groundhog,Country of Birth,0.65,0.594079,0.65,0.65

### Approach 2

In [27]:
import tapas
import pandas as pd

In [28]:
# extra metrics 
def f1_micro(y_true, y_pred):
    return f1_score(y_true, y_pred, average="micro")

def recall_weighted(y_true, y_pred):
    return recall_score(y_true, y_pred, average="weighted")

#### MIA

In [29]:
class ExtendedAttackSummary():
    
    def __init__(self, extra_metrics):
        self.extra_metrics = extra_metrics
    
    def get_metrics(self):
        """
        Calculates all MIA relevant metrics and returns it as a dataframe.

        Returns
        -------
        A dataframe
            A dataframe with attack info and metrics.  The dataframe has the following structure.
            Index:
                RangeIndex
            Columns:
                accuracy: float
                ... metrics passed as extra_metrics argument

        """
        if len(self.extra_metrics) == 0:
            return pd.DataFrame()
         
        return pd.DataFrame([[ex(self.labels, self.predictions) for ex in self.extra_metrics]], columns=[ex.__name__ for ex in self.extra_metrics],)

In [30]:
class MIAttackSummary(tapas.report.attack_summary.MIAttackSummary, ExtendedAttackSummary):
    """
    Class summarising main performance metrics of a label-inference attack with additionally passed metrics

    """

    def __init__(self,
                 labels,
                 predictions,
                 scores=None,
                 generator_info="",
                 attack_info="",
                 dataset_info="",
                 target_id="",
                 extra_metrics=[], ):
        """
        Parameters
        ----------
        labels: list[int]
            List with true labels of the target membership in the dataset.
        predictions: list[int]
            List with the predicted labels of the target membership in the dataset.
        scores: list[float]
            List with the scores related to each prediction.
        extra_metrics: list[function or Metric]
            list of function for metrics calculation 
        """
        tapas.report.attack_summary.MIAttackSummary.__init__(self, labels, predictions, scores, generator_info, attack_info, dataset_info, target_id)
        ExtendedAttackSummary.__init__(self, extra_metrics)
        

    def get_metrics(self):
        """
        Calculates all MIA relevant metrics and returns it as a dataframe.

        Returns
        -------
        A dataframe
            A dataframe with attack info and metrics.  The dataframe has the following structure.
            Index:
                RangeIndex
            Columns:
                accuracy: float
                ... metrics passed as extra_metrics argument

        """
        return pd.concat(
                [tapas.report.attack_summary.MIAttackSummary.get_metrics(self), 
                 ExtendedAttackSummary.get_metrics(self)], axis=1
        )

In [31]:
class TargetedMIA(tapas.threat_models.TargetedMIA):

    def __init__(self, extra_metrics =[], **kwargs ):
        super().__init__(**kwargs)
        self.extra_metrics = extra_metrics
        
    def _wrap_output(self, truth_labels, pred_labels, scores, attack):
        if len(self.extra_metrics) == 0:
            return super()._wrap_output(truth_labels, pred_labels, scores, attack)
        
        return MIAttackSummary(
            truth_labels,
            pred_labels,
            scores,
            generator_info=self.atk_know_gen.label,
            attack_info=attack.label,
            dataset_info=self.atk_know_data.label,
            target_id=self.target_record.label,
            extra_metrics = self.extra_metrics
        )

In [32]:
# Defining a threat model 
threat_model_mia_ext = TargetedMIA(
    attacker_knowledge_data=data_knowledge,
    target_record=target_record,
    attacker_knowledge_generator=sdg_knowledge,
    generate_pairs=True,
    replace_target=True,
    extra_metrics=[f1_micro, recall_weighted]
)
attack_mia_ext = tapas.attacks.GroundhogAttack(
    use_hist=False, use_corr=False, label="NaiveGroundhog"
)

attack_mia_ext.train(threat_model_mia_ext,num_samples=100)
summary_mia_ext = threat_model_mia_ext.test(attack_mia_ext, num_samples=100)
report_mia_ext = tapas.report.MIAttackReport([summary_mia_ext])

In [33]:
report_mia_ext.attacks_data

,dataset,target_id,generator,attack,accuracy,true_positive_rate,false_positive_rate,mia_advantage,privacy_gain,auc,effective_epsilon,f1_micro,recall_weighted
0,Census (AUX),1,Raw,NaiveGroundhog,0.54,0.34,0.26,0.08,0.92,0.5946,0.619039,0.54,0.54

#### AIA

In [34]:
class AIAttackSummary(tapas.report.attack_summary.AIAttackSummary, ExtendedAttackSummary):
    """
    Class summarising main performance metrics of a label-inference attack with additionally passed metrics

    """

    def __init__(self, 
                 labels, 
                 predictions, 
                 scores, 
                 generator_info="",
                 attack_info="",
                 dataset_info="",
                 target_id="",
                 sensitive_attribute="",
                 extra_metrics=[], ):
        """
        Parameters
        ----------
        labels: list[int]
            List with true labels of the target membership in the dataset.
        predictions: list[int]
            List with the predicted labels of the target membership in the dataset.
        scores: list[float]
            List with the scores related to each prediction.
        extra_metrics: list[function or Metric]
            list of function for metrics calculation 
        """
        tapas.report.attack_summary.AIAttackSummary.__init__(self, labels, predictions, scores, generator_info, attack_info, dataset_info, target_id, sensitive_attribute, )
        ExtendedAttackSummary.__init__(self, extra_metrics)
        

    def get_metrics(self):
        """
        Calculates all MIA relevant metrics and returns it as a dataframe.

        Returns
        -------
        A dataframe
            A dataframe with attack info and metrics.  The dataframe has the following structure.
            Index:
                RangeIndex
            Columns:
                accuracy: float
                ... metrics passed as extra_metrics argument

        """
        return pd.concat(
                [tapas.report.attack_summary.AIAttackSummary.get_metrics(self), 
                 ExtendedAttackSummary.get_metrics(self)], axis=1
        )

In [35]:
class TargetedAIA(tapas.threat_models.TargetedAIA):

    def __init__(self, extra_metrics =[], **kwargs ):
        super().__init__(**kwargs)
        self.extra_metrics = extra_metrics
        
    def _wrap_output(self, truth_labels, pred_labels, scores, attack):
        if len(self.extra_metrics) == 0:
            return super()._wrap_output(truth_labels, pred_labels, scores, attack)
        
        return AIAttackSummary(
            truth_labels,
            pred_labels,
            scores,
            generator_info=self.atk_know_gen.label,
            attack_info=attack.label,
            dataset_info=self.atk_know_data.label,
            target_id=self.target_record.label,
            sensitive_attribute=self.sensitive_attribute,
            extra_metrics = self.extra_metrics
        )

In [36]:
threat_model_extended = TargetedAIA(
    attacker_knowledge_data=data_knowledge,
    # Specific to AIA: the sensitive attribute and its possible values.
    sensitive_attribute="Country of Birth",
    attribute_values=["-9", "1", "2"],
    target_record=target_record,
    attacker_knowledge_generator=sdg_knowledge,
    extra_metrics=[f1_micro, recall_weighted]
)

attack_extended =tapas.attacks.GroundhogAttack()
attack_extended.train(threat_model_extended, num_samples=100)

summary_extended = threat_model_extended.test(attack_extended, num_samples=100)
report_extended = tapas.report.MIAttackReport([summary_extended])  
report_extended.attacks_data

/Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

,dataset,target_id,generator,attack,sensitive_attribute,accuracy,f1_micro,recall_weighted
0,Census (AUX),1,Raw,Groundhog,Country of Birth,0.64,0.64,0.64

### Approach 3

In [37]:
class ExtendedAttackSummary():

    def __init__(self, original_attack_summary,  *args, **kwargs):
        self.extra_metrics = kwargs.pop("extra_metrics", None)
        self._original_instance = original_attack_summary(*args, **kwargs)
    
    def get_metrics(self):
        return pd.concat(
                [self._original_instance.get_metrics(), 
                 pd.DataFrame([[ex(self.labels, self.predictions) for ex in self.extra_metrics]], columns=[ex.__name__ for ex in self.extra_metrics],)], axis=1
        )

    def __getattr__(self, name):
        # Delegate attribute access to the original instance
        return getattr(self._original_instance, name)


def extend_threat_model(threat_model, extra_metrics):
    
    cls = type(threat_model)

    ReportClass = tapas.report.attack_summary.MIAttackSummary
    kwargs = {}
    if isinstance(threat_model, tapas.threat_models.TargetedAIA):
        kwargs = {"sensitive_attribute": threat_model.sensitive_attribute}
        if len(threat_model.attribute_values) == 2:
            ReportClass = tapas.report.attack_summary.BinaryAIAttackSummary
            kwargs["positive_value"] = threat_model.attribute_values[1]
        else:
            ReportClass = tapas.report.attack_summary.AIAttackSummary

    class ExtendedClass(cls):
        def __init__(self, super_obj, extra_metrics):
            self.extra_metrics = extra_metrics
            for k, v in vars(super_obj).items():
                setattr(self, k, v)

        def _wrap_output(self, truth_labels, pred_labels, scores, attack):
            if len(self.extra_metrics) == 0:
                return cls._wrap_output(self, truth_labels, pred_labels, scores, attack)
            
            return ExtendedAttackSummary(
                ReportClass,
                truth_labels,
                pred_labels,
                scores,
                generator_info=self.atk_know_gen.label,
                attack_info=attack.label,
                dataset_info=self.atk_know_data.label,
                target_id=self.target_record.label,
                extra_metrics = self.extra_metrics,
                **kwargs
            )
        
    return ExtendedClass(threat_model, extra_metrics)

In [38]:
threat_model_extended = tapas.threat_models.TargetedAIA(
    attacker_knowledge_data=data_knowledge,
    # Specific to AIA: the sensitive attribute and its possible values.
    sensitive_attribute="Country of Birth",
    attribute_values=["-9", "1", "2"],
    target_record=target_record,
    attacker_knowledge_generator=sdg_knowledge
)
threat_model_extended = extend_threat_model(threat_model_extended, [f1_micro, recall_weighted])

attack_extended =tapas.attacks.GroundhogAttack()
attack_extended.train(threat_model_extended, num_samples=100)

summary_extended = threat_model_extended.test(attack_extended, num_samples=100)
report_extended = tapas.report.MIAttackReport([summary_extended])  
report_extended.attacks_data

/Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/Users/olesia/opt/anaconda3/envs/myenv/lib/python3.10/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

,dataset,target_id,generator,attack,sensitive_attribute,accuracy,f1_micro,recall_weighted
0,Census (AUX),1,Raw,Groundhog,Country of Birth,0.68,0.68,0.68

In [39]:
# Defining a threat model 
threat_model_mia_ext = tapas.threat_models.TargetedMIA(
    attacker_knowledge_data=data_knowledge,
    target_record=target_record,
    attacker_knowledge_generator=sdg_knowledge,
    generate_pairs=True,
    replace_target=True,
)

threat_model_mia_ext = extend_threat_model(threat_model_mia_ext, [f1_micro, recall_weighted])

attack_mia_ext = tapas.attacks.GroundhogAttack(
    use_hist=False, use_corr=False, label="NaiveGroundhog"
)

attack_mia_ext.train(threat_model_mia_ext,num_samples=100)
summary_mia_ext = threat_model_mia_ext.test(attack_mia_ext, num_samples=100)
report_mia_ext = tapas.report.MIAttackReport([summary_mia_ext])
report_mia_ext.attacks_data

,dataset,target_id,generator,attack,accuracy,true_positive_rate,false_positive_rate,mia_advantage,privacy_gain,auc,effective_epsilon,f1_micro,recall_weighted
0,Census (AUX),1,Raw,NaiveGroundhog,0.53,0.6,0.54,0.06,0.94,0.5618,0.916291,0.53,0.53